### ISSUE TITLE
Can't create account

### ISSUE THREAD

**Issue by tinykidpro** [batec2/CoupOnline#118]
When install and run, i try Create Account but Nothing happens
I looked at the backend terminal and saw a 404 error as follows:
```
GET /players/byName/newaccount 404 3.329 ms - 27
{ userName: 'newaccount' }
GET /players/byName/newaccount 404 2.949 ms - 27
{ userName: 'newaccount' }
GET /players/byName/newaccount 404 4.115 ms - 27
```
At the web browser console when registering, it reports errors
```
Uncaught (in promise) 
Object { stack: "AxiosError@http://127.0.0.1:5173/CoupOnline/node_modules/.vite/deps/axios.js?v=df137229:377:18\nhandleError@http://127.0.0.1:5173/CoupOnline/node_modules/.vite/deps/axios.js?v=df137229:1450:14\n", message: "Network Error", name: "AxiosError", code: "ERR_NETWORK", config: {…}, request: XMLHttpRequest }
```
Am I misconfigured or missing something? Please help me! Thank you

**Comment by batec2** [comment]
Hi, you'll need to be running a mongodb database named couponline for the backend to connect to, you can find the connection string in ```./backend/database/database.js```. If you need to know what collections to make you can find them in ```./backend/model/```, although the collections should be make automatically if the backed is able to connect to your db.

You'll also need a .env file in the frontend folder with this entry ```VITE_SERVER_URL="http://localhost:8080"```.

Because this was a school project, it's unmaintained until me or any of my group members decide to make any changes. As a result, this is probably as much help as I can give.

Good luck on creating your own project!
